/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/pQ2nzpkDfL2
 */
import Link from "next/link"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function Component() {
  return (
    (<div className="flex flex-col min-h-[100dvh]">
      <header className="px-4 lg:px-6 h-14 flex items-center">
        {/*<Link className="flex items-center justify-center" href="#">
          <MountainIcon className="h-6 w-6"/>
          <span className="sr-only">Acme Inc</span>
        </Link>*/}
        <nav className="ml-auto flex gap-4 sm:gap-6">
          <Link
            className="text-sm font-medium hover:underline underline-offset-4"
            href="#">
            Projects
          </Link>
          <Link
            className="text-sm font-medium hover:underline underline-offset-4"
            href="#">
            Skills
          </Link>
          {/*<Link
              className="text-sm font-medium hover:underline underline-offset-4"
              href="#">
            Experience
          </Link>*/}
          <Link
            className="text-sm font-medium hover:underline underline-offset-4"
            href="#">
            Contact
          </Link>
        </nav>
      </header>
      <main className="flex-1">
        <section className="w-full py-12 md:py-24 lg:py-32 xl:py-48">
          <div
            className="container flex flex-col items-center justify-center space-y-4 px-4 md:px-6">
            <div className="space-y-2 text-center">
              <h1
                className="text-4xl font-bold tracking-tighter sm:text-5xl lg:text-6xl/none">Hi, I'm Sachin Rathod</h1>
              <p
                className="max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                Backend Developer with a passion for building scalable and efficient systems.
              </p>
            </div>
            <div className="flex flex-col gap-2 min-[400px]:flex-row">
              <Link
                className="inline-flex h-10 items-center justify-center rounded-md border border-gray-200 bg-white px-8 text-sm font-medium shadow-sm transition-colors hover:bg-gray-100 hover:text-gray-900 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:border-gray-800 dark:bg-gray-950 dark:hover:bg-gray-800 dark:hover:text-gray-50 dark:focus-visible:ring-gray-300 dark:border-gray-800"
                href='SR_Resume_v1_2.pdf' download={'resume.pdf'} >
                Download CV
              </Link>
              <Link
                className="inline-flex h-10 items-center justify-center rounded-md bg-gray-900 px-8 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-gray-900/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-50/90 dark:focus-visible:ring-gray-300"
                href='mailto:sat60saheb@gmail.com'>
                Contact Me
              </Link>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 border-t">
          <div className="container px-4 md:px-6">
            <div className="grid gap-6 md:gap-12 lg:grid-cols-2">
              <div className="flex flex-col gap-2">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">My Projects</h2>
                <p
                  className="max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                  I love to work on projects that solve real-world problems. Here are some of my recent ones.
                </p>
              </div>
              <div className="grid gap-4 md:grid-cols-2">
                <div className="flex flex-col gap-1">
                  <h3 className="text-xl font-bold">Project 1</h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    Description of the project goes here. It's a really cool project that does amazing things.
                  </p>
                </div>
                <div className="flex flex-col gap-1">
                  <h3 className="text-xl font-bold">Project 2</h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    Description of the project goes here. It's a really cool project that does amazing things.
                  </p>
                </div>
                <div className="flex flex-col gap-1">
                  <h3 className="text-xl font-bold">Project 3</h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    Description of the project goes here. It's a really cool project that does amazing things.
                  </p>
                </div>
                <div className="flex flex-col gap-1">
                  <h3 className="text-xl font-bold">Project 4</h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    Description of the project goes here. It's a really cool project that does amazing things.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 border-t">
          <div className="container px-4 md:px-6">
            <div className="grid gap-6 md:gap-12 lg:grid-cols-2">
              <div className="flex flex-col gap-2">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">My Skills</h2>
                <p
                  className="max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                  I'm proficient in a variety of languages and tools. My skills include:
                </p>
              </div>
              <div className="grid gap-4 md:grid-cols-2">
                <ul className="grid gap-2">
                  <li>JavaScript</li>
                  <li>Python</li>
                  <li>SQL</li>
                  <li>Node.js</li>
                </ul>
                <ul className="grid gap-2">
                  <li>Java</li>
                  <li>C#</li>
                  <li>Git</li>
                  <li>Agile Methodologies</li>
                </ul>
              </div>
            </div>
          </div>
        </section>
        {/*<section className="w-full py-12 md:py-24 lg:py-32 border-t">
          <div className="container px-4 md:px-6">
            <div className="grid gap-6 md:gap-12 lg:grid-cols-2">
              <div className="flex flex-col gap-2">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">My Experience</h2>
                <p
                  className="max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                  I have worked at some amazing companies. Here are a few of them:
                </p>
              </div>
              <div className="grid gap-4 md:grid-cols-2">
                <ul className="grid gap-2">
                  <li>Google</li>
                  <li>Amazon</li>
                  <li>Microsoft</li>
                  <li>Facebook</li>
                </ul>
                <ul className="grid gap-2">
                  <li>Apple</li>
                  <li>Netflix</li>
                  <li>Slack</li>
                  <li>Zoom</li>
                </ul>
              </div>
            </div>
          </div>
        </section>*/}
        <section className="w-full py-12 md:py-24 lg:py-32 border-t">
          <div
            className="container grid items-center justify-center gap-4 px-4 text-center md:px-6">
            <div className="space-y-3">
              <h2 className="text-3xl font-bold tracking-tighter md:text-4xl/tight">Contact Me</h2>
              <p
                className="mx-auto max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                Want to work together? Have a question? Feel free to reach out.
              </p>
            </div>
            <div className="mx-auto w-full max-w-sm space-y-2">
              <form className="flex flex-col gap-2">
                <Input className="mx-auto max-w-sm" placeholder="Enter your email" type="email" />
                <Input
                  className="mx-auto max-w-sm h-[200px] resize-y"
                  placeholder="Your Message"
                  type="textarea" />
                <Button type="submit">Send Message</Button>
              </form>
            </div>
          </div>
        </section>
      </main>
      <footer
        className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t">
        <p className="text-xs text-gray-500 dark:text-gray-400">© 2024 Acme Inc. All rights reserved.</p>
        <nav className="sm:ml-auto flex gap-4 sm:gap-6">
          <Link className="text-xs hover:underline underline-offset-4" href="#">
            Terms of Service
          </Link>
          <Link className="text-xs hover:underline underline-offset-4" href="#">
            Privacy
          </Link>
        </nav>
      </footer>
    </div>)
  );
}


function MountainIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>)
  );
}
